sudo: required
language: cpp
os: linux
dist: xenial
compiler:
  - g++
before_install:
  - pip install --user cpp-coveralls
  - sudo apt update
  - sudo apt install -y libgtest-dev
script:
  - mkdir build && cd build && cmake .. && make && ./demo_unittest
after_success:
  - coveralls --gcov-options '\-lp'

